name: easytrip
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.6
  motion_tab_bar: ^2.0.4
  image_picker: ^0.8.4+4
  anim_search_bar: ^2.0.0
  scrollable_positioned_list: ^0.3.8
  timeline_tile: ^2.0.0
#  location: ^5.0.0
  http: ^0.13.4


  # 커스텀 주간 달력
  intl: ^0.19.0
  table_calendar: ^3.0.6
  flutter_localizations:
    sdk: flutter

  # 추가된 dependencies
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  provider: ^6.0.0
  motion_tab_bar_v2: ^0.3.0
  permission_handler: ^10.2.0
  kakao_flutter_sdk_navi: ^1.9.5 # 카카오내비 API 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cached_network_image: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_ez.png
    - assets/ph_food.jpg
    - assets/ph_lodgment.jpg
    - assets/ph_play.jpg
    - assets/ph_tourist.jpg
    - assets/ph_korea_food.jpeg
    - assets/ph_china_food.jpeg
    - assets/ph_japan_food.webp
    - assets/ph_italy_food.jpeg
    - assets/ph_dessert.jpeg
    - assets/text_1.txt
    - assets/text_2.txt
    - assets/150.png
    - assets/ph_profile_img_01.jpg
    - assets/ph_profile01.png
    - assets/ph_profile02.png
    - assets/ph_profile03.png
    - assets/ph_profile04.png
    - assets/ph_profile05.png
    - assets/ph_profile06.png
    - assets/ph_profile07.png
    - assets/ph_profile08.png
    - assets/ph_profile09.png
    - assets/ph_profile10.png
    - assets/ph_profile11.png
    - assets/ph_profile12.png
